--SUBQUERY
SELECT * FROM ELECTION_LIST;
SELECT * FROM NOMINEE_DETAILS;

INSERT INTO ELECTION_LIST(ID,FIRST_NAME,LAST_NAME,NOMINEE_ID,AGE,NATIONALITY,CAND_ADDRESS,PLACE,PHONE)
VALUES(2,'CHARLES','BABBAGE',1,25,'INDIA','BENGALURU','BENGALURU',56788765),
(3,'JIM','HOPPER',2,35,'INDIA','JAIPURU','DELHI',09888765),
(4,'BRUNO','HELLER',3,45,'INDIA','MANGALORE','MANGALORE',56781234);

SELECT * FROM ELECTION_LIST WHERE (NOMINEE_ID = (SELECT NOMINEE_ID FROM ELECTION_LIST WHERE LAST_NAME = 'HELLER'));

--SELECT * FROM ELECTION_LIST WHERE NOMINEE_ID = ();

--INNER JOIN OR CROSS JOIN
SELECT * FROM ELECTION_LIST
CROSS JOIN NOMINEE_DETAILS;

--LEFT AND RIGHT JOIN
SELECT * FROM ELECTION_LIST LEFT JOIN NOMINEE_DETAILS ON ELECTION_LIST.ID = NOMINEE_DETAILS.NOMINEE_ID;
SELECT * FROM ELECTION_LIST RIGHT JOIN NOMINEE_DETAILS ON ELECTION_LIST.ID = NOMINEE_DETAILS.NOMINEE_ID;

--SUBQUERY
SELECT * FROM ELECTION_LIST WHERE (NOMINEE_ID = (SELECT NOMINEE_ID FROM NOMINEE_DETAILS WHERE NOMINEE_NAME = 'BJP'));

SELECT * FROM ELECTION_LIST WHERE (FIRST_NAME IN (SELECT FIRST_NAME FROM ELECTION_LIST WHERE FIRST_NAME LIKE '%B%'));

SELECT * FROM EMPLOYEE_DETAILS;

SELECT * FROM DEPARTMENT;
SELECT * FROM EMPLOYEE_DETAILS RIGHT JOIN DEPARTMENT ON EMPLOYEE_DETAILS.EMP_IDS = DEPARTMENT.DEPT_ID ;
SELECT * FROM EMPLOYEE_DETAILS RIGHT JOIN NOMINEE_DETAILS ON EMPLOYEE_DETAILS.EMP_IDS = NOMINEE_DETAILS.NOMINEE_ID ;

SELECT * FROM STUDENT;
SELECT * FROM NOMINEE_DETAILS;

--CREATE PROCEDURE DELETESYMBOL
--@ID INT
--AS 
--BEGIN

--DELETE FROM NOMINEE_DETAILS WHERE NOMINEE_ID= @ID;

--END

--EXEC DELETESYMBOL 1;

CREATE TABLE STUDENT_DETAILS (STUDENT_NAME [VARCHAR](30), ID[INT]);

SELECT * FROM STUDENT_DETAILS;

INSERT INTO STUDENT_DETAILS(STUDENT_NAME,ID)
VALUES('ANUJ',1),('BHAALI',2),('THIRU',3);

CREATE PROCEDURE DELETESTUDENT
@ID INT,@STUDENT_NAME[VARCHAR](30), @UPDATEID INT
AS
BEGIN
UPDATE STUDENT_DETAILS SET STUDENT_NAME=@STUDENT_NAME WHERE ID=@UPDATEID;
DELETE FROM STUDENT_DETAILS WHERE ID=@ID;
END

EXEC DELETESTUDENT 1,'NAYANA',1;

--VIEW
CREATE VIEW ELECTIONDETAILS
AS
SELECT ELECTION_LIST.AGE, ELECTION_LIST.NATIONALITY,NOMINEE_DETAILS.NOMINEE_ID,ELECTION_LIST.FIRST_NAME LEFT JOIN NOMINEE_DETAILS ON ELECTION_LIST.ID = NOMINEE_DETAILS.NOMINEE_ID;


--CREATE A VIEW OF EMPLOYEE DETAILS WITH EMPLOYEE PH NO., EMP NAME,EMP SAL,EMP EXP.
--CREATE A VIEW OF EMPLOYEE DETAILS AND DEPARTMENT BY CROSS JOIN AND SELECT EMPL NAME,EMP SAL,EMP EXP,DEPT PLACE AND DEPT NAME
SELECT * FROM NOMINEE_DETAILS;
SELECT * FROM EMPLOYEE_DETAILS;

--VIEW
CREATE VIEW EMPLOYEE
AS SELECT EMPLOYEE_DETAILS.EMP_PHONE, EMPLOYEE_DETAILS.DATE_OF_BIRTH FROM LEFT JOIN NOMINEE_DETAILS ON 


SELECT 