--QUERIES
CREATE TABLE PERSON_INFO
(PERSON_ID[INT] , PERSON_NAME [VARCHAR](50), PERSON_SALARY [INT]);

SELECT * FROM PERSON_INFO;

ALTER TABLE PERSON_INFO ADD  PERSON_MAIL_ID [VARCHAR](100);

EXEC SP_RENAME 'PERSON_INFO.PERSON_MAIL_ID','MAILID','COLUMN';
ALTER TABLE PERSON_INFO ALTER COLUMN MAILID[VARCHAR](90);

ALTER TABLE PERSON_INFO DROP COLUMN PERSON_MAIL_ID;


EXEC SP_RENAME 'PERSON_INFO','PERSON';
EXEC SP_RENAME 'PERSON','PERSON_INFO';


SELECT * FROM PERSON;

INSERT INTO PERSON_INFO(PERSON_ID,PERSON_NAME,PERSON_SALARY,PERSON_MAIL_ID)
VALUES(101,'BHEEM',10000,'BHEEM@POGO.COM'),
(102,'CHUTKI',2000,'CHUTKI@POGO.COM'),
(103,'RAJU',6000,'RAJU@POGO.COM');

UPDATE PERSON_INFO SET PERSON_SALARY = 75000 WHERE PERSON_ID = 101;

SELECT * FROM PERSON_INFO WHERE PERSON_ID = 101;

UPDATE PERSON_INFO SET PERSON_SALARY = 809999 WHERE PERSON_ID = 102;
SELECT * FROM PERSON_INFO;

DELETE FROM PERSON_INFO WHERE PERSON_ID =102;

SELECT * FROM EMPLOYEE_DETAILS;

SELECT COUNT(EMP_IDS) AS COUNT_COLUMN FROM EMPLOYEE_DETAILS;

SELECT SUM(EMP_SALARY) AS TOTAL_SALARY FROM EMPLOYEE_DETAILS;

--CAN WE USE MULTIPLE SELECT STATEMENTS

UPDATE EMPLOYEE_DETAILS SET EMP_SALARY = (EMP_SALARY + EMP_SALARY * 0.5) WHERE (EMP_SALARY = 36266);

--AGGREGATION FUNCTIONS COUNT,SUM,MAX,MIN,AVG
SELECT AVG(EMP_SALARY) AS AVERAGE_AMOUNT FROM EMPLOYEE_DETAILS;

SELECT MAX(EMP_SALARY) AS MAXIMUM_AMOUNT FROM EMPLOYEE_DETAILS;

SELECT MIN(EMP_SALARY) AS MINIMUM_AMOUNT FROM EMPLOYEE_DETAILS;

--SCALAR FUNCTIONS
SELECT LOWER(EMP_NAME) AS LOWER_CASE FROM EMPLOYEE_DETAILS;

--CONCAT TAKES STRINGS, NUMBERS AS WELL
SELECT CONCAT(EMP_NAME, EMP_MAILID) AS CONCAT FROM EMPLOYEE_DETAILS;

SELECT CONCAT('BRUCE','LEE') AS CONCAT FROM EMPLOYEE_DETAILS;

SELECT CONCAT(10,20) AS CONCAT_TABLE;

SELECT LEN(9) AS NEW_LENGTH;

SELECT REVERSE(EMP_NAME) AS REVERSED_NAME FROM EMPLOYEE_DETAILS;

SELECT SUBSTRING('BRUNO',2,3) AS SUB_NAME;

--ALLIASING
SELECT  PERSON_NAME AS PERSON_ENAME FROM PERSON_INFO;

SELECT PERSON_NAME PERSON_ENAME FROM PERSON_INFO;

SELECT * FROM PERSON_INFO;

SELECT DISTINCT PERSON_ID FROM PERSON_INFO;
SELECT DISTINCT PERSON_NAME FROM PERSON_INFO;
SELECT DISTINCT PERSON_SALARY FROM PERSON_INFO;

SELECT DISTINCT * FROM PERSON_INFO;

SELECT PERSON_SALARY = (PERSON_SALARY * 12) FROM PERSON_INFO;
SELECT PERSON_SALARY AS ANNUAL_SAL FROM PERSON_INFO;


SELECT PERSON_SALARY = (PERSON_SALARY / 30)  FROM PERSON_INFO;
SELECT PERSON_SALARY AS PER_DAY_SAL FROM PERSON_INFO;

SELECT PERSON_SALARY = PERSON_SALARY + 5000 FROM PERSON_INFO;
SELECT PERSON_SALARY AS INCR_SAL FROM PERSON_INFO;

SELECT * FROM PERSON_INFO WHERE PERSON_ID = '101';

SELECT * FROM PERSON_INFO WHERE PERSON_ID != '101';

SELECT * FROM PERSON_INFO WHERE PERSON_ID<>'101';

SELECT * FROM PERSON_INFO WHERE PERSON_SALARY >= 36266; 

SELECT * FROM PERSON_INFO WHERE PERSON_SALARY <= 36266; 

SELECT * FROM PERSON_INFO WHERE PERSON_SALARY = 75000; 

SELECT * FROM PERSON_INFO WHERE PERSON_SALARY = 36266; 

SELECT * FROM PERSON_INFO WHERE PERSON_ID= '101' AND PERSON_NAME='BHEEM';

SELECT * FROM PERSON_INFO WHERE PERSON_ID='101' AND PERSON_NAME='BHEEM';


--ORDER BY==ASCENDING OR DESCENDING
SELECT * FROM EMPLOYEE_DETAILS WHERE EMP_SALARY BETWEEN 36000 AND 70000 ORDER BY EMP_SALARY ASC;

--GROUP BY
SELECT COUNT(*) FROM EMPLOYEE_DETAILS GROUP BY(EMP_DEPARTMENT);
SELECT COUNT(*) AS COLUMN_DEPT FROM EMPLOYEE_DETAILS WHERE (EMP_SALARY > 36000) GROUP BY(EMP_DEPARTMENT);
SELECT EMP_DEPARTMENT,EMP_SALARY FROM EMPLOYEE_DETAILS WHERE (EMP_SALARY >36000) GROUP BY EMP_DEPARTMENT, EMP_SALARY;
SELECT * FROM EMPLOYEE_DETAILS;

