CREATE DATABASE TFPRACTICE;
USE TFPRACTICE;

   CREATE TABLE [STUDENT](
   [STUDENT_ID] [INT] PRIMARY KEY,
   [STUDENT_NAME] [VARCHAR](20),
   [SPORTS] [VARCHAR](30),
   [BLOOD_GROUP] [VARCHAR](20),
   [AGE] [INT],
   );

   SELECT * FROM STUDENT;
   SELECT * FROM SPORTS_DETAILS;