--NO RETURN 
--CREATE PROCEDURE CREATESTUDENTS 
--@NAME VARCHAR(100)
--AS
--BEGIN

--INSERT INTO STUDENTDETAILS (NAME) VALUES(@NAME);
--END
-----------------------------------------------------------------
--WITH RETURN
-- TO ALTER THE PROCEDURE USE KEYWORD ALTER INSTAED OF CREATE

ALTER PROCEDURE CREATESTUDENTS 
@NAME VARCHAR(100)
AS
BEGIN

INSERT INTO STUDENTDETAILS (NAME) VALUES(@NAME);
SELECT * FROM STUDENTDETAILS ;
END



EXECUTE CREATESTUDENTS 'GOOGLE';

