--TO SET FOREIGN KEY CONSTRAINT AND CHECK CONSTRAINT

CREATE TABLE [NOMINEE_DETAILS]
(NOMINEE_ID [INT] CONSTRAINT PK_NOMINEE_DETAILS PRIMARY KEY, NOMINEE_NAME [VARCHAR](30),
SYMBOL [VARCHAR](30));


CREATE TABLE [ELECTION_LIST]
(ID[INT] CONSTRAINT PK_ELECTION_LIST PRIMARY KEY, FIRST_NAME [VARCHAR](30) NOT NULL,
LAST_NAME [VARCHAR](40), NOMINEE_ID [INT] CONSTRAINT FK_ELECTION_LIST FOREIGN KEY REFERENCES NOMINEE_DETAILS(NOMINEE_ID),AGE[INT] NOT NULL, NATIONALITY [VARCHAR](20) NOT NULL,
CAND_ADDRESS [VARCHAR](100), PLACE [VARCHAR](50),
PHONE [BIGINT] NOT NULL);

--1.CREATE A TABLE CALLED DEPARTMENT WHICH INCLUDES COLUMN LIKE DEPT ID, DEPT_NAME,PLACE
--2.SET DEPT_ID AS PRIMARY KEY
--3.ADD A NEW COLUMN TO THE EXISTING STUDENT TABLE CALLED DEPT ID
--4.RELATE THE 2 TABLES I.E STUDENT AND DEPARTMENT BY GIVING THE CONSTRAINT FOREIGN KEY TO STUDENT TABLE

CREATE TABLE DEPARTMENT(
DEPT_ID[INT] CONSTRAINT PF_DEPARTMENT PRIMARY KEY,
DEPT_NAME[VARCHAR](30),
PLACE[VARCHAR](50));

ALTER TABLE STUDENT ADD DEPT_IDS[INT];

SELECT * FROM STUDENT;

ALTER TABLE STUDENT ADD CONSTRAINT FK_STUDENT FOREIGN KEY(DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID) ;

INSERT INTO DEPARTMENT(DEPT_ID,DEPT_NAME,PLACE)
VALUES(101,'IT','BANGLORE'),
(102,'HR','MYSORE'),
(103,'BR','BANGLORE')

SELECT * FROM DEPARTMENT;

UPDATE STUDENT SET DEPT_IDS = 4 WHERE STUDENT_ID = 2;




SELECT * FROM EMPLOYEE_DETAILS;

--CHECH CONSTRAINTS
ALTER TABLE EMPLOYEE_DETAILS 
ADD EXPERIENCE [BIGINT] CONSTRAINT CHK_EXPERIENCE_CHECK CHECK(EXPERIENCE > 0 AND EXPERIENCE < 50);

UPDATE EMPLOYEE_DETAILS SET EXPERIENCE = 60 WHERE EMP_IDS = 2;

--DISTINCT
SELECT DISTINCT EMP_DEPARTMENT, EMP_MAILID FROM EMPLOYEE_DETAILS;

--IN
SELECT * FROM EMPLOYEE_DETAILS WHERE EMP_IDS IN(1,5);

--IF NAMES
SELECT * FROM EMPLOYEE_DETAILS WHERE EMP_NAME IN('NAYANA','NUTHANA');
--SELECT * FROM EMPLOYEE_DETAILS WHERE EMP_NAME IN('NAYANA','NUTHANA','NAYANA');

--BETWEEN
SELECT * FROM EMPLOYEE_DETAILS WHERE EMP_SALARY BETWEEN 36266 AND 36666;

INSERT INTO EMPLOYEE_DETAILS(EMP_NAME)
VALUES('NUTHANA'),
('NAMANA'),
('NAYANA'),
('HIMAGIRISH'),
('AKSHATHA'),
('AVI'),
('VAIBHAV'),
('PRAJWAL'),
('SHREYAS'),
('MEGHA');

UPDATE EMPLOYEE_DETAILS SET EXPERIENCE = 2 WHERE EMP_IDS = 1;
